export const SEED_CARS = [
  {
    id: "lightning-mcqueen",
    number: "95",
    name: "Lightning McQueen",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A hotshot rookie race car who discovers that life is about the journey, not the finish line. After getting stranded in Radiator Springs, he learns the value of friendship and community. He goes on to become a four-time Piston Cup champion and one of the most beloved racers of all time.",
    friends: ["Mater", "Sally Carrera", "Doc Hudson", "Luigi", "Guido", "Ramone", "Flo"],
    quotes: ["Ka-chow!", "I am speed.", "Float like a Cadillac, sting like a Beemer.", "I'm a precision instrument of speed and aerodynamics.", "Speed. I am speed."],
    color: "#c1272d",
    images: [],
    image: "lightning-mcqueen.png"
  },
  {
    id: "mater",
    number: "",
    name: "Tow Mater",
    sponsor: "Radiator Springs",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A rusty but lovable tow truck and Lightning McQueen's best friend. Despite his simple appearance, Mater has a heart of gold and a surprising talent for backwards driving. In Cars 2, he gets caught up in an international spy adventure.",
    friends: ["Lightning McQueen", "Holley Shiftwell", "Finn McMissile", "Sally Carrera"],
    quotes: ["Tuh-mater, but without the 'tuh'.", "Dad gum!", "I'm happier than a tornado in a trailer park!", "I don't need to know where I'm goin', just need to know where I've been.", "Git-R-Done!"],
    color: "#b5651d",
    images: [],
    image: "mater.png"
  },
  {
    id: "sally-carrera",
    number: "",
    name: "Sally Carrera",
    sponsor: "Cozy Cone Motel",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "The town attorney of Radiator Springs and owner of the Cozy Cone Motel. A 2002 Porsche 911 who left behind a fast-paced life in Los Angeles to find peace in the small desert town. She becomes Lightning McQueen's love interest.",
    friends: ["Lightning McQueen", "Mater", "Flo", "Ramone"],
    quotes: ["Ka-chow.", "You've been wrong about a lot of things today, Sheriff. You could be wrong about this too.", "I fell in love. I fell in love with this."],
    color: "#5ba3cf",
    images: [],
    image: "sally-carrera.png"
  },
  {
    id: "doc-hudson",
    number: "51",
    name: "Doc Hudson",
    sponsor: "Fabulous Hudson Hornet",
    movies: ["Cars", "Cars 3"],
    bio: "The wise and mysterious town doctor and judge of Radiator Springs. Secretly the legendary Fabulous Hudson Hornet, a three-time Piston Cup champion whose career was cut short by a devastating crash. He becomes Lightning McQueen's mentor.",
    friends: ["Lightning McQueen", "Sheriff", "Smokey"],
    quotes: ["All right, I wanna know who's responsible for wrecking my town, Sheriff.", "These are good folk around here, who care about one another.", "There was a lot left in me. I never got a chance to show 'em."],
    color: "#1a3c5c",
    images: [],
    image: "doc-hudson.png"
  },
  {
    id: "chick-hicks",
    number: "86",
    name: "Chick Hicks",
    sponsor: "Hostile Takeover Bank",
    movies: ["Cars", "Cars 3"],
    bio: "Lightning McQueen's fierce rival, a perpetual runner-up who has spent his entire career in The King's shadow. An arrogant, unsportsmanlike racer willing to cheat and wreck other cars to win. Later becomes a racing commentator on RSN.",
    friends: [],
    quotes: ["The Piston Cup — it's mine, dude, it's mine!", "Ka-chicka! Ka-chicka!", "Hey, McQueen, that ain't gonna work on me, buddy!"],
    color: "#2d8a3e",
    images: [],
    image: "chick-hicks.png"
  },
  {
    id: "the-king",
    number: "43",
    name: "Strip 'The King' Weathers",
    sponsor: "Dinoco",
    movies: ["Cars", "Cars 3"],
    bio: "A legendary seven-time Piston Cup champion modeled after Richard Petty's Plymouth Superbird. The King is one of the most respected racers in the sport, beloved for his sportsmanship and grace. His final race is a pivotal moment in Cars.",
    friends: ["Lightning McQueen", "Tex Dinoco", "Mrs. The King"],
    quotes: ["You ain't gonna win unless you got good folks behind ya.", "You just gave up the Piston Cup, you know that?"],
    color: "#1e90ff",
    images: [],
    image: "the-king.png"
  },
  {
    id: "ramone",
    number: "",
    name: "Ramone",
    sponsor: "Ramone's House of Body Art",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A 1959 Chevrolet Impala lowrider and owner of Ramone's House of Body Art, the local custom body and paint shop. A laid-back artist who repaints himself every day because business is slow. Married to Flo.",
    friends: ["Flo", "Lightning McQueen", "Mater", "Luigi"],
    quotes: ["Nice paint job, man!", "Yeah, baby!", "Ramone will paint you up right!"],
    color: "#8b00ff",
    images: [],
    image: "ramone.png"
  },
  {
    id: "flo",
    number: "",
    name: "Flo",
    sponsor: "Flo's V8 Cafe",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Owner of Flo's V8 Cafe, the only gas station in Radiator Springs. A sassy 1950s show car who serves the finest fuel in fifty states. She is Ramone's wife and the social hub of the town.",
    friends: ["Ramone", "Sally Carrera", "Lightning McQueen"],
    quotes: ["I have gas! Lots of gas!", "The finest fuel in fifty states!"],
    color: "#00b4d8",
    images: [],
    image: "flo.png"
  },
  {
    id: "luigi",
    number: "",
    name: "Luigi",
    sponsor: "Luigi's Casa Della Tires",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A 1959 Fiat 500 and owner of the local tire shop. An enthusiastic Italian car who dreams of Ferrari and is part of Lightning McQueen's pit crew. He is best friends with his forklift assistant Guido.",
    friends: ["Guido", "Lightning McQueen", "Mater"],
    quotes: ["Pit stop!", "Luigi follow only the Ferraris.", "Tires! Tires! Beautiful tires!"],
    color: "#f0d000",
    images: [],
    image: "luigi.png"
  },
  {
    id: "guido",
    number: "",
    name: "Guido",
    sponsor: "Luigi's Casa Della Tires",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Luigi's tiny forklift assistant and the fastest tire changer in Carburetor County. Despite speaking only Italian, Guido is a vital member of Lightning McQueen's pit crew and proved his incredible speed in the big Piston Cup race.",
    friends: ["Luigi", "Lightning McQueen"],
    quotes: ["Pit stop!", "(speaks Italian excitedly)"],
    color: "#4fc1e8",
    images: [],
    image: "guido.png"
  },
  {
    id: "sheriff",
    number: "",
    name: "Sheriff",
    sponsor: "Radiator Springs",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "The law enforcement officer of Radiator Springs. A 1949 Mercury Club Coupe who takes his job very seriously. He arrested Lightning McQueen when he first tore through town, setting the whole story in motion.",
    friends: ["Doc Hudson", "Mater", "Lightning McQueen"],
    quotes: ["Boy, you're in a heap of trouble.", "I haven't gone this fast in years!"],
    color: "#2c3e50",
    images: [],
    image: "sheriff.png"
  },
  {
    id: "sarge",
    number: "",
    name: "Sarge",
    sponsor: "Sarge's Surplus Hut",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A patriotic 1941 Willys army jeep who runs the Sarge's Surplus Hut in Radiator Springs. A former military vehicle with a strict demeanor, he has a comedic ongoing rivalry with his hippie neighbor Fillmore.",
    friends: ["Fillmore", "Lightning McQueen", "Sheriff"],
    quotes: ["It's Sarge's Surplus Hut! Come in and get your genuine surplus!", "Will you turn that disrespectful junk off?!"],
    color: "#556b2f",
    images: [],
    image: "sarge.png"
  },
  {
    id: "fillmore",
    number: "",
    name: "Fillmore",
    sponsor: "Fillmore's Taste-In",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A 1960s Volkswagen Type 2 bus and resident hippie of Radiator Springs. He runs Fillmore's Taste-In and is an expert on organic fuel. He has a classic odd-couple friendship with Sarge.",
    friends: ["Sarge", "Lightning McQueen", "Mater"],
    quotes: ["Man, I'm telling you, it's organic fuel.", "You know, some of the best fuel comes from the Earth, man.", "Respect the classics, man."],
    color: "#2ecc71",
    images: [],
    image: "fillmore.png"
  },
  {
    id: "lizzie",
    number: "",
    name: "Lizzie",
    sponsor: "Radiator Springs Curios",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "The oldest resident of Radiator Springs, a 1923 Ford Model T and widow of the town's founder, Stanley. She runs the curio shop and has a sharp tongue despite her age.",
    friends: ["Lightning McQueen", "Sally Carrera", "Red"],
    quotes: ["You keep talking to yourself, people will think you're crazy.", "Is that Stanley?"],
    color: "#2c3e50",
    images: [],
    image: "lizzie.png"
  },
  {
    id: "red",
    number: "",
    name: "Red",
    sponsor: "Radiator Springs Fire Department",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Radiator Springs' resident fire truck. A very shy and emotional vehicle who tends to his beloved flowers. Despite rarely speaking, Red is a beloved member of the community.",
    friends: ["Lizzie", "Lightning McQueen", "Mater"],
    quotes: ["(shy crying)"],
    color: "#e74c3c",
    images: [],
    image: "red.png"
  },
  {
    id: "tex-dinoco",
    number: "",
    name: "Tex Dinoco",
    sponsor: "Dinoco Oil",
    movies: ["Cars", "Cars 3"],
    bio: "The owner of Dinoco, the most prestigious sponsor in racing. A 1975 Cadillac Coupe de Ville in gold who offers Lightning McQueen a sponsorship deal, which Lightning famously declines to stay loyal to Rust-eze.",
    friends: ["The King", "Lightning McQueen"],
    quotes: ["Whatever you need, you just let me know.", "I'd like you to become the new face of Dinoco."],
    color: "#d4a80a",
    images: [],
    image: "tex-dinoco.png"
  },
  {
    id: "rusty",
    number: "",
    name: "Rusty Rust-eze",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 3"],
    bio: "One half of the Rust-eze brothers and co-owner of Rust-eze Medicated Bumper Ointment. A 1963 Dodge Dart who, along with his brother Dusty, serves as Lightning McQueen's original sponsor.",
    friends: ["Dusty Rust-eze", "Lightning McQueen"],
    quotes: ["With a little Rust-eze, and an insane amount of luck, you too can look like me!", "We might be rusty, but we still run!"],
    color: "#d35400",
    images: [],
    image: "rusty.png"
  },
  {
    id: "dusty",
    number: "",
    name: "Dusty Rust-eze",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 3"],
    bio: "One half of the Rust-eze brothers and co-owner of Rust-eze Medicated Bumper Ointment. A 1967 Dodge A100 who runs the company with his brother Rusty.",
    friends: ["Rusty Rust-eze", "Lightning McQueen"],
    quotes: ["Rust-eze!", "Use Rust-eze and you too can look like us!"],
    color: "#c0392b",
    images: [],
    image: "dusty.png"
  },
  {
    id: "boost",
    number: "",
    name: "Boost",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "The leader of the Delinquent Road Hazards, a gang of tuner cars that terrorize the highway. A modified 1990s Nissan Silvia with neon lights.",
    friends: ["DJ", "Wingo", "Snot Rod"],
    quotes: ["We got ourselves a live one!", "Who do you think you are?"],
    color: "#9b59b6",
    images: [],
    image: "boost.png"
  },
  {
    id: "dj",
    number: "",
    name: "DJ",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "A member of the Delinquent Road Hazards gang. A 2004 Scion xB equipped with a massive sound system and speakers.",
    friends: ["Boost", "Wingo", "Snot Rod"],
    quotes: ["Yo, DJ in the house!"],
    color: "#3498db",
    images: [],
    image: "dj.png"
  },
  {
    id: "wingo",
    number: "",
    name: "Wingo",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "A member of the Delinquent Road Hazards. A modified import tuner with a massive custom spoiler and wild green and purple paint job.",
    friends: ["Boost", "DJ", "Snot Rod"],
    quotes: ["Check it out!"],
    color: "#27ae60",
    images: [],
    image: "wingo.png"
  },
  {
    id: "snot-rod",
    number: "",
    name: "Snot Rod",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "A member of the Delinquent Road Hazards. A muscle car with a supercharger and terrible allergies that cause his engine to backfire uncontrollably.",
    friends: ["Boost", "DJ", "Wingo"],
    quotes: ["Ah... ah... ACHOO!"],
    color: "#e67e22",
    images: [],
    image: "snot-rod.png"
  },
  {
    id: "finn-mcmissile",
    number: "",
    name: "Finn McMissile",
    sponsor: "British Intelligence",
    movies: ["Cars 2"],
    bio: "A master British spy. A sleek Aston Martin equipped with an arsenal of gadgets including missiles, grappling hooks, and holographic disguises. He mistakes Mater for an American agent.",
    friends: ["Holley Shiftwell", "Mater", "Lightning McQueen"],
    quotes: ["My name is Finn McMissile. British Intelligence.", "I never properly introduced myself. Finn McMissile, British Intelligence."],
    color: "#34495e",
    images: [],
    image: "finn-mcmissile.png"
  },
  {
    id: "holley-shiftwell",
    number: "",
    name: "Holley Shiftwell",
    sponsor: "British Intelligence",
    movies: ["Cars 2"],
    bio: "A young but talented British spy-in-training. She is equipped with state-of-the-art spy technology and develops a romantic connection with Mater during their adventure.",
    friends: ["Finn McMissile", "Mater", "Lightning McQueen"],
    quotes: ["I'm Agent Shiftwell. Holley Shiftwell, from the British Intelligence.", "Mater, you saved the world!"],
    color: "#9b59b6",
    images: [],
    image: "holley-shiftwell.png"
  },
  {
    id: "francesco-bernoulli",
    number: "1",
    name: "Francesco Bernoulli",
    sponsor: "Formula Racing",
    movies: ["Cars 2"],
    bio: "The most famous open-wheel Formula racer in Europe and Lightning McQueen's chief rival in the World Grand Prix. An incredibly arrogant Italian racer who is constantly boasting about his speed.",
    friends: [],
    quotes: ["Francesco is triple speed!", "It's-a me, Francesco!", "No one can defeat Francesco!"],
    color: "#e74c3c",
    images: [],
    image: "francesco-bernoulli.png"
  },
  {
    id: "professor-z",
    number: "",
    name: "Professor Zundapp",
    sponsor: "Lemon Cars",
    movies: ["Cars 2"],
    bio: "The main villain of Cars 2. A sinister German weapons designer who leads a group of 'Lemon' cars in a plot to sabotage the World Grand Prix and discredit alternative fuel.",
    friends: ["Grem", "Acer"],
    quotes: ["The camera is actually a radiation emitter!", "You are being followed. Get the American spy!"],
    color: "#7f8c8d",
    images: [],
    image: "professor-z.png"
  },
  {
    id: "grem",
    number: "",
    name: "Grem",
    sponsor: "Lemon Cars",
    movies: ["Cars 2"],
    bio: "A henchman for Professor Zundapp. A rusty orange 1975 AMC Gremlin who resents being called a 'lemon.' He and Acer carry out the villain's plans in Cars 2.",
    friends: ["Acer", "Professor Zundapp"],
    quotes: ["You wanna get squished? Then shut up!"],
    color: "#d35400",
    images: [],
    image: "grem.png"
  },
  {
    id: "acer",
    number: "",
    name: "Acer",
    sponsor: "Lemon Cars",
    movies: ["Cars 2"],
    bio: "Professor Zundapp's other henchman. A lime-green AMC Pacer who works alongside Grem. He tries hard to be tough but is the more bumbling of the duo.",
    friends: ["Grem", "Professor Zundapp"],
    quotes: ["We're lemons! Nobody likes us!"],
    color: "#2ecc71",
    images: [],
    image: "acer.png"
  },
  {
    id: "shu-todoroki",
    number: "7",
    name: "Shu Todoroki",
    sponsor: "Japan",
    movies: ["Cars 2"],
    bio: "A Japanese Le Motor Prototype racer competing in the World Grand Prix. His design features a fiery red Ka-Riu dragon and represents Japan with honor.",
    friends: ["Lightning McQueen"],
    quotes: [],
    color: "#c0392b",
    images: [],
    image: "shu-todoroki.png"
  },
  {
    id: "lewis-hamilton",
    number: "2",
    name: "Lewis Hamilton",
    sponsor: "Great Britain",
    movies: ["Cars 2"],
    bio: "A British racing car competing in the World Grand Prix. Based on and voiced by real-life Formula One champion Lewis Hamilton.",
    friends: ["Lightning McQueen"],
    quotes: [],
    color: "#1a1a2e",
    images: [],
    image: "lewis-hamilton.png"
  },
  {
    id: "uncle-topolino",
    number: "",
    name: "Uncle Topolino",
    sponsor: "Porto Corsa",
    movies: ["Cars 2"],
    bio: "A wise old Fiat 500 Topolino living in Porto Corsa, Italy. He and Mama Topolino are Luigi's relatives and serve as a source of wisdom in Cars 2.",
    friends: ["Mama Topolino", "Luigi", "Guido"],
    quotes: ["Whoever finds a friend, finds a treasure."],
    color: "#2c3e50",
    images: [],
    image: "uncle-topolino.png"
  },
  {
    id: "mama-topolino",
    number: "",
    name: "Mama Topolino",
    sponsor: "Porto Corsa",
    movies: ["Cars 2"],
    bio: "Uncle Topolino's wife, a warm and loving matriarch in the Porto Corsa community. Known for her wisdom and cooking.",
    friends: ["Uncle Topolino", "Luigi", "Guido"],
    quotes: [],
    color: "#8e44ad",
    images: [],
    image: "mama-topolino.png"
  },
  {
    id: "cruz-ramirez",
    number: "51",
    name: "Cruz Ramirez",
    sponsor: "Rust-eze Racing Center",
    movies: ["Cars 3"],
    bio: "A bright yellow high-performance trainer at the Rust-eze Racing Center who grew up idolizing Lightning McQueen. Initially hired to get Lightning back in shape, she discovers her own racing talent and ultimately competes in the Florida 500, carrying on Doc Hudson's legacy with the number 51.",
    friends: ["Lightning McQueen", "Smokey", "Mater"],
    quotes: ["Cruz Ramirez, your trainer!", "I wanted to become a racer forever. Because of you!", "I can do this!"],
    color: "#f1c40f",
    images: [],
    image: "cruz-ramirez.png"
  },
  {
    id: "jackson-storm",
    number: "20",
    name: "Jackson Storm",
    sponsor: "IGNTR",
    movies: ["Cars 3"],
    bio: "The main antagonist of Cars 3. A sleek, next-generation race car who dominates the Piston Cup with cutting-edge technology and a top speed of 214 mph. Arrogant and dismissive of veteran racers.",
    friends: [],
    quotes: ["You have no idea what a pleasure it is for me to finally beat you.", "You know, you can't have the future if you're stuck in the past.", "Enjoy your retirement!"],
    color: "#2c3e50",
    images: [],
    image: "jackson-storm.png"
  },
  {
    id: "smokey",
    number: "",
    name: "Smokey",
    sponsor: "Smokey's Automotive Service",
    movies: ["Cars 3"],
    bio: "Doc Hudson's former crew chief, a 1947 Hudson pickup truck. He runs a garage in Thomasville and becomes Lightning McQueen's mentor in Cars 3, teaching him that Doc found his greatest happiness in coaching Lightning.",
    friends: ["Doc Hudson", "Lightning McQueen", "Cruz Ramirez"],
    quotes: ["All right, now you're gonna learn something new today.", "Doc saw something in you that you don't even see in yourself."],
    color: "#95a5a6",
    images: [],
    image: "smokey.png"
  },
  {
    id: "sterling",
    number: "",
    name: "Sterling",
    sponsor: "Sterling Automotive",
    movies: ["Cars 3"],
    bio: "A wealthy businessman who buys Rust-eze and becomes Lightning McQueen's new sponsor. He wants to turn Lightning into a brand rather than a racer, representing corporate greed in the racing world.",
    friends: [],
    quotes: ["Lightning McQueen is not a racer. He's a brand.", "You are a product."],
    color: "#bdc3c7",
    images: [],
    image: "sterling.png"
  },
  {
    id: "miss-fritter",
    number: "",
    name: "Miss Fritter",
    sponsor: "Thunder Hollow",
    movies: ["Cars 3"],
    bio: "A fearsome demolition derby school bus at Thunder Hollow Speedway. Equipped with a menacing stop sign blade, she is the undisputed champion of the Crazy Eight destruction derby.",
    friends: [],
    quotes: ["You about to feel the thunder!", "I'm gonna eat you alive!"],
    color: "#f39c12",
    images: [],
    image: "miss-fritter.png"
  },
  {
    id: "natalie-certain",
    number: "",
    name: "Natalie Certain",
    sponsor: "Racing Sports Network",
    movies: ["Cars 3"],
    bio: "A statistical analyst for RSN (Racing Sports Network) who uses data and analytics to predict race outcomes. She co-anchors alongside Chick Hicks in Cars 3.",
    friends: ["Chick Hicks"],
    quotes: ["Statistically speaking, Storm has a 97.6% chance of winning.", "Numbers don't lie."],
    color: "#8e44ad",
    images: [],
    image: "natalie-certain.png"
  },
  {
    id: "river-scott",
    number: "34",
    name: "River Scott",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "One of Doc Hudson's old racing rivals from the golden era of racing. A member of the Legends of Thomasville who helps train Lightning McQueen in Cars 3.",
    friends: ["Doc Hudson", "Smokey", "Lightning McQueen"],
    quotes: ["We had some great races back in the day."],
    color: "#1abc9c",
    images: [],
    image: "river-scott.png"
  },
  {
    id: "louise-nash",
    number: "94",
    name: "Louise Nash",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "A legendary female racer from the golden era and one of Doc Hudson's old rivals. She was one of the first female racers to compete at the highest level.",
    friends: ["Doc Hudson", "Smokey", "River Scott"],
    quotes: ["I had a great rivalry with the Hudson Hornet."],
    color: "#e74c3c",
    images: [],
    image: "louise-nash.png"
  },
  {
    id: "junior-moon",
    number: "",
    name: "Junior Moon",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "Another legend from Thomasville and a former moonshine runner turned racer. One of the old-school racers who helps prepare Lightning McQueen for his comeback.",
    friends: ["Doc Hudson", "Smokey", "River Scott", "Louise Nash"],
    quotes: ["Used to run moonshine right through these hills."],
    color: "#2980b9",
    images: [],
    image: "junior-moon.png"
  },
  {
    id: "mack",
    number: "",
    name: "Mack",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Lightning McQueen's loyal transport truck, a Mack Super-Liner. He hauls Lightning to all his races and is a dependable, hardworking member of the team.",
    friends: ["Lightning McQueen", "Mater"],
    quotes: ["Hey kid, we gotta go!", "I gotta stay awake..."],
    color: "#c0392b",
    images: [],
    image: "mack.png"
  },
  // ── Cars 1 – remaining characters ──────────────────────────
  {
    id: "mia-and-tia",
    number: "",
    name: "Mia & Tia",
    sponsor: "",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Twin Mazda Miatas and Lightning McQueen's biggest fans. Originally fans of Chick Hicks, they switch allegiance to McQueen after his sportsmanlike gesture at the final race.",
    friends: ["Lightning McQueen"],
    quotes: ["We love you, Lightning!"],
    color: "#e91e63",
    images: [],
    image: ""
  },
  {
    id: "lynda-weathers",
    number: "",
    name: "Lynda Weathers",
    sponsor: "",
    movies: ["Cars"],
    bio: "The wife of Strip 'The King' Weathers. She is a loyal supporter of her husband and is seen cheering him on at the Piston Cup.",
    friends: ["Strip Weathers", "Tex Dinoco"],
    quotes: ["You've sure come a long way, honey."],
    color: "#64b5f6",
    images: [],
    image: ""
  },
  {
    id: "bob-cutlass",
    number: "",
    name: "Bob Cutlass",
    sponsor: "RSN",
    movies: ["Cars", "Cars 3"],
    bio: "One half of the Piston Cup broadcasting duo alongside Darrell Cartrip. A professional and composed racing commentator for the Racing Sports Network.",
    friends: ["Darrell Cartrip"],
    quotes: ["Welcome back to what has become an incredible night of racing!"],
    color: "#546e7a",
    images: [],
    image: ""
  },
  {
    id: "darrell-cartrip",
    number: "",
    name: "Darrell Cartrip",
    sponsor: "RSN",
    movies: ["Cars", "Cars 3"],
    bio: "The enthusiastic color commentator for the Piston Cup alongside Bob Cutlass. A former racer turned broadcaster who brings energy and humor to the booth.",
    friends: ["Bob Cutlass"],
    quotes: ["Boogity boogity boogity! Let's go racing, boys!"],
    color: "#ff7043",
    images: [],
    image: ""
  },
  {
    id: "fred",
    number: "",
    name: "Fred",
    sponsor: "",
    movies: ["Cars", "Cars 2"],
    bio: "A beat-up rusty car who is a huge racing fan. He's known for his missing front bumper and enthusiastic personality despite his run-down appearance.",
    friends: ["Lightning McQueen"],
    quotes: ["He remembers my name! He knows my name!"],
    color: "#8d6e63",
    images: [],
    image: ""
  },
  {
    id: "stanley",
    number: "",
    name: "Stanley",
    sponsor: "",
    movies: ["Cars"],
    bio: "The founder of Radiator Springs and Lizzie's late husband. A statue of Stanley stands in the center of town as a tribute to his legacy.",
    friends: ["Lizzie"],
    quotes: [],
    color: "#78909c",
    images: [],
    image: ""
  },
  {
    id: "frank",
    number: "",
    name: "Frank",
    sponsor: "",
    movies: ["Cars", "Cars 3"],
    bio: "A giant, intimidating combine harvester who guards the tractor field. He chases Mater and Lightning McQueen when they go tractor tipping.",
    friends: [],
    quotes: [],
    color: "#b71c1c",
    images: [],
    image: ""
  },
  {
    id: "van",
    number: "",
    name: "Van",
    sponsor: "",
    movies: ["Cars", "Cars 2"],
    bio: "A married minivan who travels with his wife Minny. They often get lost and refuse to ask for directions, providing comic relief throughout the films.",
    friends: ["Minny"],
    quotes: ["I know exactly where we are."],
    color: "#ffc107",
    images: [],
    image: ""
  },
  {
    id: "minny",
    number: "",
    name: "Minny",
    sponsor: "",
    movies: ["Cars", "Cars 2"],
    bio: "Van's patient wife who constantly reminds him to ask for directions. A practical and level-headed minivan.",
    friends: ["Van"],
    quotes: ["Oh, for the love of Chrysler, can we please ask someone for directions?"],
    color: "#ce93d8",
    images: [],
    image: ""
  },
  {
    id: "not-chuck",
    number: "",
    name: "Not Chuck",
    sponsor: "",
    movies: ["Cars"],
    bio: "A forklift working at the Piston Cup who is frequently mistaken for someone named Chuck. His real name is never revealed.",
    friends: [],
    quotes: ["My name's not Chuck!"],
    color: "#a1887f",
    images: [],
    image: ""
  },
  {
    id: "kori-turbowitz",
    number: "",
    name: "Kori Turbowitz",
    sponsor: "RSN",
    movies: ["Cars"],
    bio: "A news reporter for the Racing Sports Network who covers the Piston Cup racing events and interviews Lightning McQueen.",
    friends: [],
    quotes: ["Lightning, how do you feel about being the first rookie in history to win the Piston Cup?"],
    color: "#4fc3f7",
    images: [],
    image: ""
  },
  {
    id: "harv",
    number: "",
    name: "Harv",
    sponsor: "",
    movies: ["Cars"],
    bio: "Lightning McQueen's agent. A fast-talking car who is always looking for the next big endorsement deal. He's only heard through the phone and never seen in person.",
    friends: ["Lightning McQueen"],
    quotes: ["Where are you? I can barely hear you!"],
    color: "#7e57c2",
    images: [],
    image: ""
  },
  // ── Cars 2 – remaining characters ──────────────────────────
  {
    id: "miles-axlerod",
    number: "",
    name: "Miles Axlerod",
    sponsor: "Allinol",
    movies: ["Cars 2"],
    bio: "A former oil baron turned environmentalist who creates Allinol alternative fuel and organizes the World Grand Prix. He is secretly the mastermind behind the Lemons' plot.",
    friends: [],
    quotes: ["Allinol is completely safe!", "Alternative fuel is the future!"],
    color: "#4caf50",
    images: [],
    image: ""
  },
  {
    id: "rod-torque-redline",
    number: "",
    name: "Rod 'Torque' Redline",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "An American spy car who is captured by the Lemons while investigating their plot. He passes crucial intelligence to Mater before being destroyed.",
    friends: ["Finn McMissile"],
    quotes: ["This intel is top secret. Do not share it with anyone."],
    color: "#1565c0",
    images: [],
    image: ""
  },
  {
    id: "siddeley",
    number: "",
    name: "Siddeley",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A British spy jet and Finn McMissile's partner. He provides air support and transportation for the spy team throughout their mission.",
    friends: ["Finn McMissile", "Holley Shiftwell"],
    quotes: ["I'm on my way!"],
    color: "#90a4ae",
    images: [],
    image: ""
  },
  {
    id: "leland-turbo",
    number: "",
    name: "Leland Turbo",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A British spy who is Finn McMissile's informant. He is captured and crushed into a cube by the Lemons early in the film.",
    friends: ["Finn McMissile"],
    quotes: ["Finn, the mission has been compromised."],
    color: "#37474f",
    images: [],
    image: ""
  },
  {
    id: "stephenson",
    number: "",
    name: "Stephenson",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A spy train who assists Finn McMissile and the team. He serves as a mobile headquarters and transport during their European mission.",
    friends: ["Finn McMissile", "Holley Shiftwell"],
    quotes: [],
    color: "#455a64",
    images: [],
    image: ""
  },
  {
    id: "tomber",
    number: "",
    name: "Tomber",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A three-wheeled Reliant Regal who is a black market parts dealer in Paris. Despite his gruff exterior, he provides crucial help to Finn and Mater.",
    friends: ["Finn McMissile"],
    quotes: ["Finn McMissile. I didn't think you would show your face here again."],
    color: "#795548",
    images: [],
    image: ""
  },
  {
    id: "jeff-gorvette",
    number: "24",
    name: "Jeff Gorvette",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "An American racing champion and Corvette who competes in the World Grand Prix. Based on Jeff Gordon, he is a friendly and respected racer.",
    friends: ["Lightning McQueen"],
    quotes: ["Hey Lightning! Good luck out there."],
    color: "#f44336",
    images: [],
    image: ""
  },
  {
    id: "rip-clutchgoneski",
    number: "",
    name: "Rip Clutchgoneski",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A Formula One race car from the Republic of New Rearendia who competes in the World Grand Prix. Known for his open-wheel racing style.",
    friends: [],
    quotes: [],
    color: "#00bcd4",
    images: [],
    image: ""
  },
  {
    id: "raoul-caroule",
    number: "6",
    name: "Raoul CaRoule",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A French rally car and World Grand Prix competitor. Known as the 'World's Greatest Rally Car,' he is a skilled and flamboyant racer from France.",
    friends: [],
    quotes: [],
    color: "#1565c0",
    images: [],
    image: ""
  },
  {
    id: "carla-veloso",
    number: "",
    name: "Carla Veloso",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A Brazilian race car who competes in the World Grand Prix. She is sleek, fast, and represents the pride of Brazilian motorsport.",
    friends: [],
    quotes: [],
    color: "#4caf50",
    images: [],
    image: ""
  },
  {
    id: "max-schnell",
    number: "",
    name: "Max Schnell",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A German endurance racer who competes in the World Grand Prix. A precision-engineered race car known for his methodical racing style.",
    friends: [],
    quotes: [],
    color: "#212121",
    images: [],
    image: ""
  },
  {
    id: "nigel-gearsley",
    number: "9",
    name: "Nigel Gearsley",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A British race car from Warwickshire who competes in the World Grand Prix. An Aston Martin-inspired racer known for his composure on the track.",
    friends: [],
    quotes: [],
    color: "#2e7d32",
    images: [],
    image: ""
  },
  {
    id: "miguel-camino",
    number: "",
    name: "Miguel Camino",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A Spanish race car and World Grand Prix competitor. A GT-style racer who represents Spain with flair and passion.",
    friends: [],
    quotes: [],
    color: "#d32f2f",
    images: [],
    image: ""
  },
  {
    id: "prince-wheeliam",
    number: "",
    name: "Prince Wheeliam",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A member of the British Royal Family who attends the World Grand Prix in London. A regal and dignified character based on British royalty.",
    friends: [],
    quotes: [],
    color: "#1a237e",
    images: [],
    image: ""
  },
  {
    id: "david-hobbscap",
    number: "",
    name: "David Hobbscap",
    sponsor: "RSN",
    movies: ["Cars 2"],
    bio: "A British broadcasting legend who serves as commentator for the World Grand Prix alongside Brent Mustangburger.",
    friends: ["Brent Mustangburger"],
    quotes: [],
    color: "#607d8b",
    images: [],
    image: ""
  },
  {
    id: "brent-mustangburger",
    number: "",
    name: "Brent Mustangburger",
    sponsor: "RSN",
    movies: ["Cars 2"],
    bio: "A veteran American broadcaster who covers the World Grand Prix. An experienced and authoritative commentator modeled after Brent Musberger.",
    friends: ["David Hobbscap"],
    quotes: [],
    color: "#455a64",
    images: [],
    image: ""
  },
  {
    id: "crabby",
    number: "",
    name: "Crabby",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A crabby old fishing boat who inadvertently transports Finn McMissile near the Lemons' oil rig at the beginning of Cars 2.",
    friends: [],
    quotes: ["What are you doing out here, mate?"],
    color: "#5d4037",
    images: [],
    image: ""
  },
  {
    id: "tony-trihull",
    number: "",
    name: "Tony Trihull",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A military combat ship working for the Lemons. An imposing naval vessel that pursues Finn McMissile during the opening sequence.",
    friends: [],
    quotes: [],
    color: "#37474f",
    images: [],
    image: ""
  },
  {
    id: "tubbs-pacer",
    number: "",
    name: "Tubbs Pacer",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A member of the Lemons gang and leader of the Pacers family. One of the henchmen working under Professor Zündapp.",
    friends: ["Professor Zundapp"],
    quotes: [],
    color: "#827717",
    images: [],
    image: ""
  },
  {
    id: "j-curby-gremlin",
    number: "",
    name: "J. Curby Gremlin",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "The leader of the Gremlins faction of the Lemons. A small but devious henchman working in Professor Zündapp's organization.",
    friends: ["Professor Zundapp"],
    quotes: [],
    color: "#558b2f",
    images: [],
    image: ""
  },
  {
    id: "vladimir-trunkov",
    number: "",
    name: "Vladimir Trunkov",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "The head of the Trunkov family within the Lemons criminal organization. A Zaporozhets who is part of the villainous conspiracy.",
    friends: ["Professor Zundapp"],
    quotes: [],
    color: "#4e342e",
    images: [],
    image: ""
  },
  {
    id: "victor-hugo",
    number: "",
    name: "Victor Hugo",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "The leader of the Hugo family of Lemons. A large, imposing tow truck who serves as muscle for the criminal organization.",
    friends: ["Professor Zundapp"],
    quotes: [],
    color: "#bf360c",
    images: [],
    image: ""
  },
  {
    id: "ivan",
    number: "",
    name: "Ivan",
    sponsor: "",
    movies: ["Cars 2"],
    bio: "A tow truck working for the Lemons. He is assigned to guard Mater during the events at the World Grand Prix in London.",
    friends: [],
    quotes: [],
    color: "#616161",
    images: [],
    image: ""
  },
  // ── Cars 3 – remaining characters ──────────────────────────
  {
    id: "shannon-spokes",
    number: "",
    name: "Shannon Spokes",
    sponsor: "RSN",
    movies: ["Cars 3"],
    bio: "A Racing Sports Network journalist who covers the new generation of racers. She reports on Jackson Storm's rise and Lightning McQueen's struggles.",
    friends: [],
    quotes: ["Lightning McQueen has reportedly been seen training at the old Thomasville track."],
    color: "#ec407a",
    images: [],
    image: ""
  },
  {
    id: "chase-racelott",
    number: "48",
    name: "Chase Racelott",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation Piston Cup racer who represents the new wave of high-tech race cars competing alongside Jackson Storm.",
    friends: [],
    quotes: [],
    color: "#0d47a1",
    images: [],
    image: ""
  },
  {
    id: "ryan-laney",
    number: "21",
    name: "Ryan 'Inside' Laney",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A veteran Piston Cup racer who survives the transition to the next generation. Known for his tenacity and determination on the track.",
    friends: ["Lightning McQueen"],
    quotes: [],
    color: "#1b5e20",
    images: [],
    image: ""
  },
  {
    id: "danny-swervez",
    number: "19",
    name: "Danny Swervez",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation race car and one of the new rookies challenging the veterans in the Piston Cup circuit.",
    friends: [],
    quotes: [],
    color: "#e65100",
    images: [],
    image: ""
  },
  {
    id: "bubba-wheelhouse",
    number: "84",
    name: "Bubba Wheelhouse",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation Piston Cup racer. Part of the new wave of technologically advanced race cars that push Lightning McQueen toward retirement.",
    friends: [],
    quotes: [],
    color: "#6a1b9a",
    images: [],
    image: ""
  },
  {
    id: "brick-yardley",
    number: "24",
    name: "Brick Yardley",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A veteran Piston Cup racer who is among the old guard being replaced by next-gen racers. Eventually pushed out of the sport.",
    friends: ["Lightning McQueen", "Cal Weathers"],
    quotes: [],
    color: "#ff6f00",
    images: [],
    image: ""
  },
  {
    id: "bobby-swift",
    number: "19",
    name: "Bobby Swift",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A veteran Piston Cup racer and one of Lightning McQueen's contemporaries who gets replaced by a next-generation rookie.",
    friends: ["Lightning McQueen", "Cal Weathers"],
    quotes: [],
    color: "#0277bd",
    images: [],
    image: ""
  },
  {
    id: "cal-weathers",
    number: "42",
    name: "Cal Weathers",
    sponsor: "Dinoco",
    movies: ["Cars 3"],
    bio: "The nephew of Strip 'The King' Weathers and the current Dinoco-sponsored racer. A veteran competitor who is eventually replaced by a next-gen rookie.",
    friends: ["Lightning McQueen", "Strip Weathers"],
    quotes: [],
    color: "#0288d1",
    images: [],
    image: ""
  },
  {
    id: "maddy-mcgear",
    number: "",
    name: "Maddy McGear",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A young fan of Lightning McQueen who cheers him on during the events of Cars 3. She represents the next generation of racing fans.",
    friends: [],
    quotes: ["You can do it, McQueen!"],
    color: "#f48fb1",
    images: [],
    image: ""
  },
  {
    id: "dr-damage",
    number: "63",
    name: "Dr. Damage",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A demolition derby competitor at the Thunder Hollow Speedway. A tough, aggressive racer in the dirt track circuit.",
    friends: ["Miss Fritter"],
    quotes: [],
    color: "#b71c1c",
    images: [],
    image: ""
  },
  {
    id: "apb",
    number: "",
    name: "APB",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A demolition derby racer at Thunder Hollow who resembles a police car. One of the colorful competitors in the rough-and-tumble dirt track scene.",
    friends: ["Miss Fritter"],
    quotes: [],
    color: "#283593",
    images: [],
    image: ""
  },
  {
    id: "arvy",
    number: "",
    name: "Arvy",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A demolition derby competitor at Thunder Hollow Speedway. An RV-type vehicle who participates in the chaotic races.",
    friends: ["Miss Fritter"],
    quotes: [],
    color: "#4e342e",
    images: [],
    image: ""
  },
  {
    id: "cam-spinner",
    number: "31",
    name: "Cam Spinner",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation racer in the Piston Cup series. One of the high-tech rookies who brings advanced technology to the racing circuit.",
    friends: [],
    quotes: [],
    color: "#00838f",
    images: [],
    image: ""
  },
  {
    id: "flip-dover",
    number: "",
    name: "Flip Dover",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation Piston Cup racer who is part of the new wave replacing veteran racers in the circuit.",
    friends: [],
    quotes: [],
    color: "#33691e",
    images: [],
    image: ""
  },
  {
    id: "harvey-rodcap",
    number: "",
    name: "Harvey Rodcap",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A veteran Piston Cup racer from the older generation of competitors in the racing circuit.",
    friends: [],
    quotes: [],
    color: "#4a148c",
    images: [],
    image: ""
  },
  {
    id: "jd-mcpillar",
    number: "",
    name: "J.D. McPillar",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation Piston Cup racer who joins the circuit as part of the new crop of technologically advanced competitors.",
    friends: [],
    quotes: [],
    color: "#880e4f",
    images: [],
    image: ""
  },
  {
    id: "rich-mixon",
    number: "",
    name: "Rich Mixon",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A demolition derby competitor at Thunder Hollow Speedway who makes life difficult for Lightning McQueen during his unexpected stint in the mud.",
    friends: ["Miss Fritter"],
    quotes: [],
    color: "#3e2723",
    images: [],
    image: ""
  },
  {
    id: "reb-meeker",
    number: "",
    name: "Reb Meeker",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "One of the Legends of Thomasville and an old racing rival of Doc Hudson from the golden era of racing.",
    friends: ["Doc Hudson", "Smokey", "Louise Nash", "River Scott"],
    quotes: [],
    color: "#bf360c",
    images: [],
    image: ""
  },
  {
    id: "phil-tankson",
    number: "",
    name: "Phil Tankson",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation Piston Cup racer who is among the new breed of high-tech race cars entering the circuit.",
    friends: [],
    quotes: [],
    color: "#004d40",
    images: [],
    image: ""
  },
  {
    id: "buck-bearingly",
    number: "",
    name: "Buck Bearingly",
    sponsor: "",
    movies: ["Cars 3"],
    bio: "A next-generation Piston Cup racer and part of the wave of technologically superior rookies who challenge the veteran racers.",
    friends: [],
    quotes: [],
    color: "#1a237e",
    images: [],
    image: ""
  },
  // ── Cars on the Road (COTR) ────────────────────────────────
  {
    id: "ivy",
    number: "",
    name: "Ivy",
    sponsor: "",
    movies: ["COTR"],
    bio: "A free-spirited electric car who Mater befriends during his road trip with Lightning McQueen in the Cars on the Road series.",
    friends: ["Mater", "Lightning McQueen"],
    quotes: [],
    color: "#66bb6a",
    images: [],
    image: ""
  }
];
