export const SEED_CARS = [
  {
    id: "lightning-mcqueen",
    number: "95",
    name: "Lightning McQueen",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A hotshot rookie race car who discovers that life is about the journey, not the finish line. After getting stranded in Radiator Springs, he learns the value of friendship and community. He goes on to become a four-time Piston Cup champion and one of the most beloved racers of all time.",
    friends: ["Mater", "Sally Carrera", "Doc Hudson", "Luigi", "Guido", "Ramone", "Flo"],
    quotes: ["Ka-chow!", "I am speed.", "Float like a Cadillac, sting like a Beemer.", "I'm a precision instrument of speed and aerodynamics.", "Speed. I am speed."],
    color: "#c1272d",
    image: "lightning-mcqueen.png"
  },
  {
    id: "mater",
    number: "",
    name: "Tow Mater",
    sponsor: "Radiator Springs",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A rusty but lovable tow truck and Lightning McQueen's best friend. Despite his simple appearance, Mater has a heart of gold and a surprising talent for backwards driving. In Cars 2, he gets caught up in an international spy adventure.",
    friends: ["Lightning McQueen", "Holley Shiftwell", "Finn McMissile", "Sally Carrera"],
    quotes: ["Tuh-mater, but without the 'tuh'.", "Dad gum!", "I'm happier than a tornado in a trailer park!", "I don't need to know where I'm goin', just need to know where I've been.", "Git-R-Done!"],
    color: "#b5651d",
    image: "mater.png"
  },
  {
    id: "sally-carrera",
    number: "",
    name: "Sally Carrera",
    sponsor: "Cozy Cone Motel",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "The town attorney of Radiator Springs and owner of the Cozy Cone Motel. A 2002 Porsche 911 who left behind a fast-paced life in Los Angeles to find peace in the small desert town. She becomes Lightning McQueen's love interest.",
    friends: ["Lightning McQueen", "Mater", "Flo", "Ramone"],
    quotes: ["Ka-chow.", "You've been wrong about a lot of things today, Sheriff. You could be wrong about this too.", "I fell in love. I fell in love with this."],
    color: "#5ba3cf",
    image: "sally-carrera.png"
  },
  {
    id: "doc-hudson",
    number: "51",
    name: "Doc Hudson",
    sponsor: "Fabulous Hudson Hornet",
    movies: ["Cars", "Cars 3"],
    bio: "The wise and mysterious town doctor and judge of Radiator Springs. Secretly the legendary Fabulous Hudson Hornet, a three-time Piston Cup champion whose career was cut short by a devastating crash. He becomes Lightning McQueen's mentor.",
    friends: ["Lightning McQueen", "Sheriff", "Smokey"],
    quotes: ["All right, I wanna know who's responsible for wrecking my town, Sheriff.", "These are good folk around here, who care about one another.", "There was a lot left in me. I never got a chance to show 'em."],
    color: "#1a3c5c",
    image: "doc-hudson.png"
  },
  {
    id: "chick-hicks",
    number: "86",
    name: "Chick Hicks",
    sponsor: "Hostile Takeover Bank",
    movies: ["Cars", "Cars 3"],
    bio: "Lightning McQueen's fierce rival, a perpetual runner-up who has spent his entire career in The King's shadow. An arrogant, unsportsmanlike racer willing to cheat and wreck other cars to win. Later becomes a racing commentator on RSN.",
    friends: [],
    quotes: ["The Piston Cup — it's mine, dude, it's mine!", "Ka-chicka! Ka-chicka!", "Hey, McQueen, that ain't gonna work on me, buddy!"],
    color: "#2d8a3e",
    image: "chick-hicks.png"
  },
  {
    id: "the-king",
    number: "43",
    name: "Strip 'The King' Weathers",
    sponsor: "Dinoco",
    movies: ["Cars", "Cars 3"],
    bio: "A legendary seven-time Piston Cup champion modeled after Richard Petty's Plymouth Superbird. The King is one of the most respected racers in the sport, beloved for his sportsmanship and grace. His final race is a pivotal moment in Cars.",
    friends: ["Lightning McQueen", "Tex Dinoco", "Mrs. The King"],
    quotes: ["You ain't gonna win unless you got good folks behind ya.", "You just gave up the Piston Cup, you know that?"],
    color: "#1e90ff",
    image: "the-king.png"
  },
  {
    id: "ramone",
    number: "",
    name: "Ramone",
    sponsor: "Ramone's House of Body Art",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A 1959 Chevrolet Impala lowrider and owner of Ramone's House of Body Art, the local custom body and paint shop. A laid-back artist who repaints himself every day because business is slow. Married to Flo.",
    friends: ["Flo", "Lightning McQueen", "Mater", "Luigi"],
    quotes: ["Nice paint job, man!", "Yeah, baby!", "Ramone will paint you up right!"],
    color: "#8b00ff",
    image: "ramone.png"
  },
  {
    id: "flo",
    number: "",
    name: "Flo",
    sponsor: "Flo's V8 Cafe",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Owner of Flo's V8 Cafe, the only gas station in Radiator Springs. A sassy 1950s show car who serves the finest fuel in fifty states. She is Ramone's wife and the social hub of the town.",
    friends: ["Ramone", "Sally Carrera", "Lightning McQueen"],
    quotes: ["I have gas! Lots of gas!", "The finest fuel in fifty states!"],
    color: "#00b4d8",
    image: "flo.png"
  },
  {
    id: "luigi",
    number: "",
    name: "Luigi",
    sponsor: "Luigi's Casa Della Tires",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A 1959 Fiat 500 and owner of the local tire shop. An enthusiastic Italian car who dreams of Ferrari and is part of Lightning McQueen's pit crew. He is best friends with his forklift assistant Guido.",
    friends: ["Guido", "Lightning McQueen", "Mater"],
    quotes: ["Pit stop!", "Luigi follow only the Ferraris.", "Tires! Tires! Beautiful tires!"],
    color: "#f0d000",
    image: "luigi.png"
  },
  {
    id: "guido",
    number: "",
    name: "Guido",
    sponsor: "Luigi's Casa Della Tires",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Luigi's tiny forklift assistant and the fastest tire changer in Carburetor County. Despite speaking only Italian, Guido is a vital member of Lightning McQueen's pit crew and proved his incredible speed in the big Piston Cup race.",
    friends: ["Luigi", "Lightning McQueen"],
    quotes: ["Pit stop!", "(speaks Italian excitedly)"],
    color: "#4fc1e8",
    image: "guido.png"
  },
  {
    id: "sheriff",
    number: "",
    name: "Sheriff",
    sponsor: "Radiator Springs",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "The law enforcement officer of Radiator Springs. A 1949 Mercury Club Coupe who takes his job very seriously. He arrested Lightning McQueen when he first tore through town, setting the whole story in motion.",
    friends: ["Doc Hudson", "Mater", "Lightning McQueen"],
    quotes: ["Boy, you're in a heap of trouble.", "I haven't gone this fast in years!"],
    color: "#2c3e50",
    image: "sheriff.png"
  },
  {
    id: "sarge",
    number: "",
    name: "Sarge",
    sponsor: "Sarge's Surplus Hut",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A patriotic 1941 Willys army jeep who runs the Sarge's Surplus Hut in Radiator Springs. A former military vehicle with a strict demeanor, he has a comedic ongoing rivalry with his hippie neighbor Fillmore.",
    friends: ["Fillmore", "Lightning McQueen", "Sheriff"],
    quotes: ["It's Sarge's Surplus Hut! Come in and get your genuine surplus!", "Will you turn that disrespectful junk off?!"],
    color: "#556b2f",
    image: "sarge.png"
  },
  {
    id: "fillmore",
    number: "",
    name: "Fillmore",
    sponsor: "Fillmore's Taste-In",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "A 1960s Volkswagen Type 2 bus and resident hippie of Radiator Springs. He runs Fillmore's Taste-In and is an expert on organic fuel. He has a classic odd-couple friendship with Sarge.",
    friends: ["Sarge", "Lightning McQueen", "Mater"],
    quotes: ["Man, I'm telling you, it's organic fuel.", "You know, some of the best fuel comes from the Earth, man.", "Respect the classics, man."],
    color: "#2ecc71",
    image: "fillmore.png"
  },
  {
    id: "lizzie",
    number: "",
    name: "Lizzie",
    sponsor: "Radiator Springs Curios",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "The oldest resident of Radiator Springs, a 1923 Ford Model T and widow of the town's founder, Stanley. She runs the curio shop and has a sharp tongue despite her age.",
    friends: ["Lightning McQueen", "Sally Carrera", "Red"],
    quotes: ["You keep talking to yourself, people will think you're crazy.", "Is that Stanley?"],
    color: "#2c3e50",
    image: "lizzie.png"
  },
  {
    id: "red",
    number: "",
    name: "Red",
    sponsor: "Radiator Springs Fire Department",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Radiator Springs' resident fire truck. A very shy and emotional vehicle who tends to his beloved flowers. Despite rarely speaking, Red is a beloved member of the community.",
    friends: ["Lizzie", "Lightning McQueen", "Mater"],
    quotes: ["(shy crying)"],
    color: "#e74c3c",
    image: "red.png"
  },
  {
    id: "tex-dinoco",
    number: "",
    name: "Tex Dinoco",
    sponsor: "Dinoco Oil",
    movies: ["Cars", "Cars 3"],
    bio: "The owner of Dinoco, the most prestigious sponsor in racing. A 1975 Cadillac Coupe de Ville in gold who offers Lightning McQueen a sponsorship deal, which Lightning famously declines to stay loyal to Rust-eze.",
    friends: ["The King", "Lightning McQueen"],
    quotes: ["Whatever you need, you just let me know.", "I'd like you to become the new face of Dinoco."],
    color: "#d4a80a",
    image: "tex-dinoco.png"
  },
  {
    id: "rusty",
    number: "",
    name: "Rusty Rust-eze",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 3"],
    bio: "One half of the Rust-eze brothers and co-owner of Rust-eze Medicated Bumper Ointment. A 1963 Dodge Dart who, along with his brother Dusty, serves as Lightning McQueen's original sponsor.",
    friends: ["Dusty Rust-eze", "Lightning McQueen"],
    quotes: ["With a little Rust-eze, and an insane amount of luck, you too can look like me!", "We might be rusty, but we still run!"],
    color: "#d35400",
    image: "rusty.png"
  },
  {
    id: "dusty",
    number: "",
    name: "Dusty Rust-eze",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 3"],
    bio: "One half of the Rust-eze brothers and co-owner of Rust-eze Medicated Bumper Ointment. A 1967 Dodge A100 who runs the company with his brother Rusty.",
    friends: ["Rusty Rust-eze", "Lightning McQueen"],
    quotes: ["Rust-eze!", "Use Rust-eze and you too can look like us!"],
    color: "#c0392b",
    image: "dusty.png"
  },
  {
    id: "boost",
    number: "",
    name: "Boost",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "The leader of the Delinquent Road Hazards, a gang of tuner cars that terrorize the highway. A modified 1990s Nissan Silvia with neon lights.",
    friends: ["DJ", "Wingo", "Snot Rod"],
    quotes: ["We got ourselves a live one!", "Who do you think you are?"],
    color: "#9b59b6",
    image: "boost.png"
  },
  {
    id: "dj",
    number: "",
    name: "DJ",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "A member of the Delinquent Road Hazards gang. A 2004 Scion xB equipped with a massive sound system and speakers.",
    friends: ["Boost", "Wingo", "Snot Rod"],
    quotes: ["Yo, DJ in the house!"],
    color: "#3498db",
    image: "dj.png"
  },
  {
    id: "wingo",
    number: "",
    name: "Wingo",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "A member of the Delinquent Road Hazards. A modified import tuner with a massive custom spoiler and wild green and purple paint job.",
    friends: ["Boost", "DJ", "Snot Rod"],
    quotes: ["Check it out!"],
    color: "#27ae60",
    image: "wingo.png"
  },
  {
    id: "snot-rod",
    number: "",
    name: "Snot Rod",
    sponsor: "Delinquent Road Hazards",
    movies: ["Cars"],
    bio: "A member of the Delinquent Road Hazards. A muscle car with a supercharger and terrible allergies that cause his engine to backfire uncontrollably.",
    friends: ["Boost", "DJ", "Wingo"],
    quotes: ["Ah... ah... ACHOO!"],
    color: "#e67e22",
    image: "snot-rod.png"
  },
  {
    id: "finn-mcmissile",
    number: "",
    name: "Finn McMissile",
    sponsor: "British Intelligence",
    movies: ["Cars 2"],
    bio: "A master British spy. A sleek Aston Martin equipped with an arsenal of gadgets including missiles, grappling hooks, and holographic disguises. He mistakes Mater for an American agent.",
    friends: ["Holley Shiftwell", "Mater", "Lightning McQueen"],
    quotes: ["My name is Finn McMissile. British Intelligence.", "I never properly introduced myself. Finn McMissile, British Intelligence."],
    color: "#34495e",
    image: "finn-mcmissile.png"
  },
  {
    id: "holley-shiftwell",
    number: "",
    name: "Holley Shiftwell",
    sponsor: "British Intelligence",
    movies: ["Cars 2"],
    bio: "A young but talented British spy-in-training. She is equipped with state-of-the-art spy technology and develops a romantic connection with Mater during their adventure.",
    friends: ["Finn McMissile", "Mater", "Lightning McQueen"],
    quotes: ["I'm Agent Shiftwell. Holley Shiftwell, from the British Intelligence.", "Mater, you saved the world!"],
    color: "#9b59b6",
    image: "holley-shiftwell.png"
  },
  {
    id: "francesco-bernoulli",
    number: "1",
    name: "Francesco Bernoulli",
    sponsor: "Formula Racing",
    movies: ["Cars 2"],
    bio: "The most famous open-wheel Formula racer in Europe and Lightning McQueen's chief rival in the World Grand Prix. An incredibly arrogant Italian racer who is constantly boasting about his speed.",
    friends: [],
    quotes: ["Francesco is triple speed!", "It's-a me, Francesco!", "No one can defeat Francesco!"],
    color: "#e74c3c",
    image: "francesco-bernoulli.png"
  },
  {
    id: "professor-z",
    number: "",
    name: "Professor Zundapp",
    sponsor: "Lemon Cars",
    movies: ["Cars 2"],
    bio: "The main villain of Cars 2. A sinister German weapons designer who leads a group of 'Lemon' cars in a plot to sabotage the World Grand Prix and discredit alternative fuel.",
    friends: ["Grem", "Acer"],
    quotes: ["The camera is actually a radiation emitter!", "You are being followed. Get the American spy!"],
    color: "#7f8c8d",
    image: "professor-z.png"
  },
  {
    id: "grem",
    number: "",
    name: "Grem",
    sponsor: "Lemon Cars",
    movies: ["Cars 2"],
    bio: "A henchman for Professor Zundapp. A rusty orange 1975 AMC Gremlin who resents being called a 'lemon.' He and Acer carry out the villain's plans in Cars 2.",
    friends: ["Acer", "Professor Zundapp"],
    quotes: ["You wanna get squished? Then shut up!"],
    color: "#d35400",
    image: "grem.png"
  },
  {
    id: "acer",
    number: "",
    name: "Acer",
    sponsor: "Lemon Cars",
    movies: ["Cars 2"],
    bio: "Professor Zundapp's other henchman. A lime-green AMC Pacer who works alongside Grem. He tries hard to be tough but is the more bumbling of the duo.",
    friends: ["Grem", "Professor Zundapp"],
    quotes: ["We're lemons! Nobody likes us!"],
    color: "#2ecc71",
    image: "acer.png"
  },
  {
    id: "shu-todoroki",
    number: "7",
    name: "Shu Todoroki",
    sponsor: "Japan",
    movies: ["Cars 2"],
    bio: "A Japanese Le Motor Prototype racer competing in the World Grand Prix. His design features a fiery red Ka-Riu dragon and represents Japan with honor.",
    friends: ["Lightning McQueen"],
    quotes: [],
    color: "#c0392b",
    image: "shu-todoroki.png"
  },
  {
    id: "lewis-hamilton",
    number: "2",
    name: "Lewis Hamilton",
    sponsor: "Great Britain",
    movies: ["Cars 2"],
    bio: "A British racing car competing in the World Grand Prix. Based on and voiced by real-life Formula One champion Lewis Hamilton.",
    friends: ["Lightning McQueen"],
    quotes: [],
    color: "#1a1a2e",
    image: "lewis-hamilton.png"
  },
  {
    id: "uncle-topolino",
    number: "",
    name: "Uncle Topolino",
    sponsor: "Porto Corsa",
    movies: ["Cars 2"],
    bio: "A wise old Fiat 500 Topolino living in Porto Corsa, Italy. He and Mama Topolino are Luigi's relatives and serve as a source of wisdom in Cars 2.",
    friends: ["Mama Topolino", "Luigi", "Guido"],
    quotes: ["Whoever finds a friend, finds a treasure."],
    color: "#2c3e50",
    image: "uncle-topolino.png"
  },
  {
    id: "mama-topolino",
    number: "",
    name: "Mama Topolino",
    sponsor: "Porto Corsa",
    movies: ["Cars 2"],
    bio: "Uncle Topolino's wife, a warm and loving matriarch in the Porto Corsa community. Known for her wisdom and cooking.",
    friends: ["Uncle Topolino", "Luigi", "Guido"],
    quotes: [],
    color: "#8e44ad",
    image: "mama-topolino.png"
  },
  {
    id: "cruz-ramirez",
    number: "51",
    name: "Cruz Ramirez",
    sponsor: "Rust-eze Racing Center",
    movies: ["Cars 3"],
    bio: "A bright yellow high-performance trainer at the Rust-eze Racing Center who grew up idolizing Lightning McQueen. Initially hired to get Lightning back in shape, she discovers her own racing talent and ultimately competes in the Florida 500, carrying on Doc Hudson's legacy with the number 51.",
    friends: ["Lightning McQueen", "Smokey", "Mater"],
    quotes: ["Cruz Ramirez, your trainer!", "I wanted to become a racer forever. Because of you!", "I can do this!"],
    color: "#f1c40f",
    image: "cruz-ramirez.png"
  },
  {
    id: "jackson-storm",
    number: "20",
    name: "Jackson Storm",
    sponsor: "IGNTR",
    movies: ["Cars 3"],
    bio: "The main antagonist of Cars 3. A sleek, next-generation race car who dominates the Piston Cup with cutting-edge technology and a top speed of 214 mph. Arrogant and dismissive of veteran racers.",
    friends: [],
    quotes: ["You have no idea what a pleasure it is for me to finally beat you.", "You know, you can't have the future if you're stuck in the past.", "Enjoy your retirement!"],
    color: "#2c3e50",
    image: "jackson-storm.png"
  },
  {
    id: "smokey",
    number: "",
    name: "Smokey",
    sponsor: "Smokey's Automotive Service",
    movies: ["Cars 3"],
    bio: "Doc Hudson's former crew chief, a 1947 Hudson pickup truck. He runs a garage in Thomasville and becomes Lightning McQueen's mentor in Cars 3, teaching him that Doc found his greatest happiness in coaching Lightning.",
    friends: ["Doc Hudson", "Lightning McQueen", "Cruz Ramirez"],
    quotes: ["All right, now you're gonna learn something new today.", "Doc saw something in you that you don't even see in yourself."],
    color: "#95a5a6",
    image: "smokey.png"
  },
  {
    id: "sterling",
    number: "",
    name: "Sterling",
    sponsor: "Sterling Automotive",
    movies: ["Cars 3"],
    bio: "A wealthy businessman who buys Rust-eze and becomes Lightning McQueen's new sponsor. He wants to turn Lightning into a brand rather than a racer, representing corporate greed in the racing world.",
    friends: [],
    quotes: ["Lightning McQueen is not a racer. He's a brand.", "You are a product."],
    color: "#bdc3c7",
    image: "sterling.png"
  },
  {
    id: "miss-fritter",
    number: "",
    name: "Miss Fritter",
    sponsor: "Thunder Hollow",
    movies: ["Cars 3"],
    bio: "A fearsome demolition derby school bus at Thunder Hollow Speedway. Equipped with a menacing stop sign blade, she is the undisputed champion of the Crazy Eight destruction derby.",
    friends: [],
    quotes: ["You about to feel the thunder!", "I'm gonna eat you alive!"],
    color: "#f39c12",
    image: "miss-fritter.png"
  },
  {
    id: "natalie-certain",
    number: "",
    name: "Natalie Certain",
    sponsor: "Racing Sports Network",
    movies: ["Cars 3"],
    bio: "A statistical analyst for RSN (Racing Sports Network) who uses data and analytics to predict race outcomes. She co-anchors alongside Chick Hicks in Cars 3.",
    friends: ["Chick Hicks"],
    quotes: ["Statistically speaking, Storm has a 97.6% chance of winning.", "Numbers don't lie."],
    color: "#8e44ad",
    image: "natalie-certain.png"
  },
  {
    id: "river-scott",
    number: "34",
    name: "River Scott",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "One of Doc Hudson's old racing rivals from the golden era of racing. A member of the Legends of Thomasville who helps train Lightning McQueen in Cars 3.",
    friends: ["Doc Hudson", "Smokey", "Lightning McQueen"],
    quotes: ["We had some great races back in the day."],
    color: "#1abc9c",
    image: "river-scott.png"
  },
  {
    id: "louise-nash",
    number: "94",
    name: "Louise Nash",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "A legendary female racer from the golden era and one of Doc Hudson's old rivals. She was one of the first female racers to compete at the highest level.",
    friends: ["Doc Hudson", "Smokey", "River Scott"],
    quotes: ["I had a great rivalry with the Hudson Hornet."],
    color: "#e74c3c",
    image: "louise-nash.png"
  },
  {
    id: "junior-moon",
    number: "",
    name: "Junior Moon",
    sponsor: "Thomasville Racing",
    movies: ["Cars 3"],
    bio: "Another legend from Thomasville and a former moonshine runner turned racer. One of the old-school racers who helps prepare Lightning McQueen for his comeback.",
    friends: ["Doc Hudson", "Smokey", "River Scott", "Louise Nash"],
    quotes: ["Used to run moonshine right through these hills."],
    color: "#2980b9",
    image: "junior-moon.png"
  },
  {
    id: "mack",
    number: "",
    name: "Mack",
    sponsor: "Rust-eze",
    movies: ["Cars", "Cars 2", "Cars 3"],
    bio: "Lightning McQueen's loyal transport truck, a Mack Super-Liner. He hauls Lightning to all his races and is a dependable, hardworking member of the team.",
    friends: ["Lightning McQueen", "Mater"],
    quotes: ["Hey kid, we gotta go!", "I gotta stay awake..."],
    color: "#c0392b",
    image: "mack.png"
  }
];
